### ISSUE TITLE
Conventional designations of Fused Comb cells 

### ISSUE THREAD

**Issue by ogamespec** [rgalland/SNES_S-CPU_Schematics#1]
NANDNANDNAND and similar cells are usually called AOI / OAI.

Their names are quite simple, you can look for example here (the first link from google):

https://tams.informatik.uni-hamburg.de/applets/hades/webdemos/10-gates/00-gates/complex.html

So this, for example AND2_NOR3.png is actually `211-AOI`

**Comment by rgalland** [comment]
Thanks, this is a much better naming convention. I'll make the edits whenever I can.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: ogamespec ***@***.***>
Sent: Wednesday, June 14, 2023 1:28:19 PM
To: rgalland/SNES_S-CPU_Schematics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rgalland/SNES_S-CPU_Schematics] Conventional designations of Fused Comb cells (Issue #1)


NANDNANDNAND and similar cells are usually called AOI / OAI.

Their names are quite simple, you can look for example here (the first link from google):

https://tams.informatik.uni-hamburg.de/applets/hades/webdemos/10-gates/00-gates/complex.html

So this, for example AND2_NOR3.png is actually 211-AOI

**Comment by rgalland** [comment]
Reopened as a reminder

**Comment by rgalland** [comment]
Seems that all gate shave been identified now. AOI and OAI terminology used to name name complex gates.
